# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SJVJ QNA
email: l-jiayee@comp.nus.edu.sg
description: > # this means to ignore newlines until "baseurl:"
  A journey of 365 questions, 5 years, 1825 answers, 4 friends
baseurl: "/sjvj-qna" # the subpath of your site, e.g. /blog
url: "https://jiayeerawr.github.io" # the base hostname & protocol for your site
# twitter_username: 
github_username:  jiayeerawr

# Build settings
markdown: kramdown
